var JSON;
KeyboardEvent.prototype.keyLocation;
HTMLCanvasElement.prototype.webkitImageSmoothingEnabled;
HTMLCanvasElement.prototype.mozImageSmoothingEnabled;
HTMLCanvasElement.prototype.imageSmoothingEnabled;
