#!/usr/bin/env node
// Copyright 2014-2015 Ben Trask
// MIT licensed (see LICENSE for details)

var sln = require("../sln-client");

if(process.argv.length <= 2) {
	console.error("Usage: sln-query repo [query]");
	process.exit(1);
}
var repo = sln.repoForName(process.argv[2]);
var query = process.argv[3] || "";

var stream = repo.createQueryStream(query, {});
stream.on("data", function(URI) {
	console.log(URI);
});

