#!/usr/bin/env node
// Copyright 2014-2015 Ben Trask
// MIT licensed (see LICENSE for details)

var sln = require("../sln-client");

if(process.argv.length <= 4) {
	console.error("Usage: sln-add-tags repo [tag ...] query");
	process.exit(1);
}
var repo = sln.repoForName(process.argv[2]);
var tags = process.argv.slice(3, -1);
var query = process.argv.slice(-1)[0];

function array2obj(array) {
	var obj = {};
	for(var i = 0; i < array.length; i++) {
		obj[array[i]] = {};
	}
	return obj;
}

var meta = {
	"tag": array2obj(tags),
};

var stream = repo.createQueryStream(query, { wait: false });
stream.on("data", function(URI) {
	stream.pause();
	repo.submitMeta(URI, meta, {}, function(err, obj) {
		if(err) throw err;
		stream.resume();
		console.log(URI);
	});
});

