#!/usr/bin/env node
// Copyright 2014-2015 Ben Trask
// MIT licensed (see LICENSE for details)

var sln = require("../sln-client");
var repo = sln.mainRepo();

function array2obj(array) {
	var obj = {};
	for(var i = 0; i < array.length; i++) {
		obj[array[i]] = {};
	}
	return obj;
}

if(process.argv.length < 3) {
	console.error("Usage: "+process.argv[1]+" <tag> [...] <query>");
	process.exit(1);
}
var query = process.argv.slice(-1)[0];
var meta = {
	"tag": array2obj(process.argv.slice(2, -1)),
};

var stream = repo.createQueryStream(query, { wait: false });
stream.on("data", function(URI) {
	stream.pause();
	repo.submitMeta(URI, meta, {}, function(err, obj) {
		if(err) throw err;
		stream.resume();
		console.log(URI);
	});
});

