#!/usr/bin/env node
// Copyright 2014-2015 Ben Trask
// MIT licensed (see LICENSE for details)

var fs = require("fs");
var pathmodule = require("path");

var sln = require("../sln-client");
var mime = require("./mime"); // TODO: Unused so far.

if(process.argv.length <= 2) {
	console.error("Usage: sln-export <repository>");
	process.exit(1);
}
var repo = sln.repoForName(process.argv[2]);

function has(obj, prop) {
	return Object.prototype.hasOwnProperty.call(obj, prop);
}
function earliest(obj) {
	if(!obj) return null;
	return Object.keys(obj).sort()[0] || null;
}
function mkdirp_dirname(path, mode, cb) {
	var dir = pathmodule.dirname(path);
	fs.mkdir(dir, mode, function(err) {
		if(!err) return cb(null);
		if("EEXIST" === err.code) return cb(null);
		if("ENOENT" !== err.code) return cb(err);
		mkdirp_dirname(dir, mode, function(err) {
			if(err) return cb(err);
			fs.mkdir(dir, mode, cb);
		});
	});
}

var q = process.argv[2] || "";

var stream = repo.createQueryStream(q, { wait: false });
stream.on("data", function(URI) {
	stream.pause();
	repo.getMeta(URI, {}, function(err, metadata) {
		if(err) throw err;
		var path = earliest(metadata["source-path"]);
		if(!path) {
			var title = earliest(metadata["title"]);
			if(!title) {
				title = sln.parseURI(URI).hash;
			}
			// TODO: Make sure path extension makes sense.
			path = "./unknown/"+title;
		}
		// TODO: Verify that path does not escape the cwd.
		console.log(path);
		mkdirp_dirname(path, 0777, function(err) {
			if(err) throw err;
			var req = repo.createFileRequest(URI, {});
			req.on("response", function(res) {
				var dst = fs.createWriteStream(path);
				res.pipe(dst);
				res.on("end", function() {
					stream.resume();
				});
			});
		});
	});
});

